version: '3.5'
services:
  mw-link-fetcher:
    container_name: mw-link-fetcher
    restart: unless-stopped
    build:
      context: .
      dockerfile: config/Dockerfile
    environment:
      NODE_ENV: production
      MODULE_NAME: mw-link-fetcher
      PORT: 80
    ports:
      - 80:80
    networks:
      - network-bridge
    command: npm start
networks:
  network-bridge:
    driver: bridge
